plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/ryanpederson/Dev/websites/CatLife/catlife-phaser-v2"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]